spring:
  profiles:
    include: oauth

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true

  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    port: 6379
    host: localhost




# 로그 레벨 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정
    org.springframework.security.web: trace

# sendError 했을 때 반환하는 필드 컨트롤
# 실무에서는 exception, message, stacktrace, binding-errors를 반환하면 안되고 로그로 처리해야한다.
# never 사용하지 않음
# always 항상 사용
# on_param 파라미터가 있을 때 사용
server:
  error:
    include-stacktrace: never


jwt:
  secret-key: test
  # 1시간
  access-expiration-time: 3600000
  # 24시간
  refresh-expiration-time: 86400000